= Mule 4 OpenTelemetry (OTel) Agent Extension
// Document header
Rick Bansal <rick.bansal@mulesoft.com>
:revnumber: 1.3.0
:revdate: June 27, 2023
:revremark: 
:doctype: book
:icons: font
:toc: left
:keywords: Mule, MuleSoft, Observability, OpenTelemetry, OTel, Tracing, Instrumentation, Distributed

// The following pass through will align the images and their titles
ifndef::env-github[]
++++
<style>
  .imageblock > .title {
    text-align: inherit;
    margin-top: 10px;
  }
</style>
++++
endif::[]

ifdef::env-github[]
:caution-caption: :fire:
:important-caption: :heavy_exclamation_mark:
:note-caption: :information_source:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]

//
// custom attributes
//
:html-previewer: https://htmlpreview.github.io/?
:html-version-of-README: https://github.com/rickbansal-mulesoft/otel-mule4-observability-agent/blob/main/target/generated-docs/README.html
:docs-dir: src/docs/asciidoc
:extension-jar-filepath: target/otel-mule4-observability-agent-{revnumber}-mule-plugin.jar

 
[IMPORTANT]
This work effort is a field extension; hence, it is delivered on an "*as-is*" basis.
Please refrain from contacting MuleSoft Support for technical support. Instead. use *GitHub 
Issues* to provide feedback, suggest enhancements or report a bug.

== Link to the Extension jar file

## Release Notes

### Version 1.4.15 [New Relic Labs ]

- **Add following dependency to applications pom.xml**

```xml
  <dependency>
      <groupId>com.newrelic.labs</groupId>
      <artifactId>otel-mule4-observability-agent</artifactId>
      <version>1.4.15</version>
      <classifier>mule-plugin</classifier>
  </dependency>
```
- **Header Control**: You can now configure the headers to be dropped from being sent to New Relic.

The sections to follow :

Global Element Properties -> OLTP Trace Exporter -> Custom Attributes -> Headers to be exluded ....

[Default values ]  - mw_client_id,mw_client_secret

![image](https://github.com/user-attachments/assets/7382244f-29a4-4416-947b-52cea2b8fff4)

- **JDK 17 Release**: This version is compatible with JDK 17.
- **Mule Runtime 4.9.2**: Ensure your Mule environment is running version 4.9.2 for compatibility.

### Version 1.0.2 [New Relic Labs ]

- **Dependency**

```xml
  <dependency>
      <groupId>com.newrelic.labs</groupId>
      <artifactId>otel-mule4-observability-agent</artifactId>
      <version>1.0.2</version>
      <classifier>mule-plugin</classifier>
  </dependency>
```
- **JDK 17 Release**: This version is compatible with JDK 17.
- **Mule Runtime 4.9.2**: Ensure your Mule environment is running version 4.9.2 for compatibility.


== Links to the documentation

Please refer to one of the two options below for extended documentation on this extension.

=== HTML Version - Recommended**
The HTML version is usually more presentation friendly and *preferred* for viewing this documentation.

* {html-previewer}{html-version-of-README}[Extended Documentation in HTML format]

=== ADOC Version
The adoc version doesn't always render optimally in GitHub but if you have trouble with HTML then
use this link.

//* link:src/docs/asciidoc/README.adoc[Extended Documentation in adoc format]

* link:{docs-dir}/README.adoc[Extended Documentation in adoc format]

== Backends Tested Against

include::backendsTested.adoc[]
